apiVersion: apps/v1
kind: Deployment
metadata:
  name: service_name
  labels:
    app: service_name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service_name
  template:
    metadata:
      labels:
        app: service_name
    spec:
      volumes:
        - name: workspace-volume
          emptyDir: {}
      initContainers:
        - name: copy-s3-resources
          image: amazon/aws-cli
          command: ["/bin/sh", "-c"]
          args:
            - >
              aws s3 cp s3://repl/code/service_name/ /workspace/ --recursive &&
              echo "Resources copied from S3";
          env:
            - name: SUPABASE_URL
              value: https://lrxckwrdfioeigpdlznj.supabase.co
            - name: SUPABASE_ANON_KEY
              value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyeGNrd3JkZmlvZWlncGRsem5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjMxMDMwMDIsImV4cCI6MjAzODY3OTAwMn0.ZuG3TqMUBeaCghtmxv2raVb7qgYnfyeEWSa5ujyeYRU
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace
      containers:
        - name: runner
          image: 100xdevs/runner:latest
          ports:
            - containerPort: 3001
            - containerPort: 3000
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace
          resources:
            # Bounty $25 Use ephemeral-storage to add space limits here
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"   
