apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-deployment
  labels:
    app: runner
spec:
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      volumes:
        - name: workspace-volume
          emptyDir: {}
      containers:
        - name: runner
          image: rishi91/runner:latest
          ports:
            - containerPort: 4000
            - containerPort: 5173
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace
          env:
            - name: SUPABASE_URL
              value: https://lrxckwrdfioeigpdlznj.supabase.co
            - name: SUPABASE_ANON_KEY
              value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyeGNrd3JkZmlvZWlncGRsem5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjMxMDMwMDIsImV4cCI6MjAzODY3OTAwMn0.ZuG3TqMUBeaCghtmxv2raVb7qgYnfyeEWSa5ujyeYRU
            - name: BUCKET_NAME
              value: files
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: runner-service
spec:
  selector:
    app: runner
  ports:
    - name: http-4000
      protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30007  # This will be dynamically replaced
    - name: http-5173
      protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30008  # This will be dynamically replaced
  type: NodePort