FROM node:18-alpine

RUN apk add --no-cache python3 make g++

RUN apk add --no-cache zsh

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

WORKDIR /runner

COPY package*.json ./

RUN npm install

COPY . /runner

EXPOSE 5173

EXPOSE 4000

EXPOSE 5173

CMD [ "npm","start" ]

